/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-admins': RouteRecordInfo<'admin-admins', '/admin/admins', Record<never, never>, Record<never, never>>,
    'admin-admins-create': RouteRecordInfo<'admin-admins-create', '/admin/admins/create', Record<never, never>, Record<never, never>>,
    'admin-admins-edit-id': RouteRecordInfo<'admin-admins-edit-id', '/admin/admins/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-brands': RouteRecordInfo<'admin-brands', '/admin/brands', Record<never, never>, Record<never, never>>,
    'admin-brands-create': RouteRecordInfo<'admin-brands-create', '/admin/brands/create', Record<never, never>, Record<never, never>>,
    'admin-brands-edit-id': RouteRecordInfo<'admin-brands-edit-id', '/admin/brands/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-car-features': RouteRecordInfo<'admin-car-features', '/admin/car_features', Record<never, never>, Record<never, never>>,
    'admin-car-features-create': RouteRecordInfo<'admin-car-features-create', '/admin/car_features/create', Record<never, never>, Record<never, never>>,
    'admin-car-features-edit-id': RouteRecordInfo<'admin-car-features-edit-id', '/admin/car_features/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-cars': RouteRecordInfo<'admin-cars', '/admin/cars', Record<never, never>, Record<never, never>>,
    'admin-cars-create': RouteRecordInfo<'admin-cars-create', '/admin/cars/create', Record<never, never>, Record<never, never>>,
    'admin-cars-edit-id': RouteRecordInfo<'admin-cars-edit-id', '/admin/cars/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-cities': RouteRecordInfo<'admin-cities', '/admin/cities', Record<never, never>, Record<never, never>>,
    'admin-cities-create': RouteRecordInfo<'admin-cities-create', '/admin/cities/create', Record<never, never>, Record<never, never>>,
    'admin-cities-edit-id': RouteRecordInfo<'admin-cities-edit-id', '/admin/cities/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-countries': RouteRecordInfo<'admin-countries', '/admin/countries', Record<never, never>, Record<never, never>>,
    'admin-countries-create': RouteRecordInfo<'admin-countries-create', '/admin/countries/create', Record<never, never>, Record<never, never>>,
    'admin-countries-edit-id': RouteRecordInfo<'admin-countries-edit-id', '/admin/countries/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-login': RouteRecordInfo<'admin-login', '/admin/login', Record<never, never>, Record<never, never>>,
    'admin-models': RouteRecordInfo<'admin-models', '/admin/models', Record<never, never>, Record<never, never>>,
    'admin-models-create': RouteRecordInfo<'admin-models-create', '/admin/models/create', Record<never, never>, Record<never, never>>,
    'admin-models-edit-id': RouteRecordInfo<'admin-models-edit-id', '/admin/models/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-sellers': RouteRecordInfo<'admin-sellers', '/admin/sellers', Record<never, never>, Record<never, never>>,
    'admin-sellers-create': RouteRecordInfo<'admin-sellers-create', '/admin/sellers/create', Record<never, never>, Record<never, never>>,
    'admin-sellers-edit-id': RouteRecordInfo<'admin-sellers-edit-id', '/admin/sellers/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'admin-users-create': RouteRecordInfo<'admin-users-create', '/admin/users/create', Record<never, never>, Record<never, never>>,
    'admin-users-edit-id': RouteRecordInfo<'admin-users-edit-id', '/admin/users/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'seller-brands': RouteRecordInfo<'seller-brands', '/seller/brands', Record<never, never>, Record<never, never>>,
    'seller-brands-create': RouteRecordInfo<'seller-brands-create', '/seller/brands/create', Record<never, never>, Record<never, never>>,
    'seller-brands-edit-id': RouteRecordInfo<'seller-brands-edit-id', '/seller/brands/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'seller-car-features': RouteRecordInfo<'seller-car-features', '/seller/car_features', Record<never, never>, Record<never, never>>,
    'seller-car-features-create': RouteRecordInfo<'seller-car-features-create', '/seller/car_features/create', Record<never, never>, Record<never, never>>,
    'seller-car-features-edit-id': RouteRecordInfo<'seller-car-features-edit-id', '/seller/car_features/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'seller-cars': RouteRecordInfo<'seller-cars', '/seller/cars', Record<never, never>, Record<never, never>>,
    'seller-cars-create': RouteRecordInfo<'seller-cars-create', '/seller/cars/create', Record<never, never>, Record<never, never>>,
    'seller-cars-edit-id': RouteRecordInfo<'seller-cars-edit-id', '/seller/cars/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'seller-dashboard': RouteRecordInfo<'seller-dashboard', '/seller/dashboard', Record<never, never>, Record<never, never>>,
    'seller-login': RouteRecordInfo<'seller-login', '/seller/login', Record<never, never>, Record<never, never>>,
    'seller-models': RouteRecordInfo<'seller-models', '/seller/models', Record<never, never>, Record<never, never>>,
    'seller-models-create': RouteRecordInfo<'seller-models-create', '/seller/models/create', Record<never, never>, Record<never, never>>,
    'seller-models-edit-id': RouteRecordInfo<'seller-models-edit-id', '/seller/models/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'seller-register': RouteRecordInfo<'seller-register', '/seller/register', Record<never, never>, Record<never, never>>,
    'user-cars': RouteRecordInfo<'user-cars', '/user/cars', Record<never, never>, Record<never, never>>,
    'user-cars-id': RouteRecordInfo<'user-cars-id', '/user/cars/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'user-profile': RouteRecordInfo<'user-profile', '/user/profile', Record<never, never>, Record<never, never>>,
    'user-sellers-id': RouteRecordInfo<'user-sellers-id', '/user/sellers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
