export const predefinedFeatures = [
  // الأمان والسلامة (Safety & Security)
  { ar: 'مانع انغلاق الفرامل', en: 'Anti-lock Braking System (ABS)', aliases: ['abs', 'anti-lock braking system', 'مانع انغلاق الفرامل'] },
  { ar: 'توزيع إلكتروني للفرامل', en: 'Electronic Brakeforce Distribution (EBD)', aliases: ['ebd', 'electronic brakeforce distribution', 'توزيع إلكتروني للفرامل'] },
  { ar: 'الثبات الإلكتروني', en: 'Electronic Stability Program (ESP / ESC)', aliases: ['esp', 'esc', 'electronic stability program', 'الثبات الإلكتروني'] },
  { ar: 'مانع الانزلاق', en: 'Traction Control System (TCS)', aliases: ['tcs', 'traction control system', 'مانع الانزلاق'] },
  { ar: 'مساعد الفرامل', en: 'Brake Assist (BA)', aliases: ['ba', 'brake assist', 'مساعد الفرامل'] },
  { ar: 'فرامل طوارئ تلقائية', en: 'Autonomous Emergency Braking (AEB)', aliases: ['aeb', 'autonomous emergency braking', 'فرامل طوارئ تلقائية'] },
  { ar: 'تحذير الاصطدام الأمامي', en: 'Forward Collision Warning (FCW)', aliases: ['fcw', 'forward collision warning', 'تحذير الاصطدام الأمامي'] },
  { ar: 'مساعد تفادي الاصطدام', en: 'Collision Avoidance Assist', aliases: ['collision avoidance assist', 'مساعد تفادي الاصطدام'] },
  { ar: 'مراقبة النقطة العمياء', en: 'Blind Spot Monitoring (BSM)', aliases: ['bsm', 'blind spot monitoring', 'مراقبة النقطة العمياء', 'نظام مراقبة النقاط العمياء'] },
  { ar: 'المحافظة على المسار', en: 'Lane Keep Assist (LKA)', aliases: ['lka', 'lane keep assist', 'المحافظة على المسار'] },
  { ar: 'تحذير الخروج من الحارة', en: 'Lane Departure Warning (LDW)', aliases: ['ldw', 'lane departure warning', 'تحذير الخروج من الحارة', 'تنبيه مغادرة المسار'] },
  { ar: 'مساعد التمركز في الحارة', en: 'Lane Centering Assist', aliases: ['lane centering', 'lane centering assist', 'تمركز داخل الحارة', 'مساعد التمركز في الحارة'] },
  { ar: 'مثبت سرعة متكيف', en: 'Adaptive Cruise Control (ACC)', aliases: ['acc', 'adaptive cruise control', 'مثبت سرعة متكيف'] },
  { ar: 'التعرف على الإشارات', en: 'Traffic Sign Recognition (TSR)', aliases: ['tsr', 'traffic sign recognition', 'التعرف على الإشارات'] },
  { ar: 'تنبيه انتباه السائق', en: 'Driver Attention Alert', aliases: ['driver attention alert', 'تنبيه انتباه السائق'] },
  { ar: 'تنبيه حركة خلفية', en: 'Rear Cross Traffic Alert (RCTA)', aliases: ['rcta', 'rear cross traffic alert', 'تنبيه حركة خلفية'] },
  { ar: 'مساعد الركن', en: 'Park Assist', aliases: ['park assist', 'مساعد الركن'] },
  { ar: 'مساعد الركن التلقائي', en: 'Automatic Parking Assist', aliases: ['automatic parking assist', 'مساعد الركن التلقائي'] },
  { ar: 'ركن ذاتي', en: 'Self Parking / Auto Park', aliases: ['self parking', 'auto park', 'ركن ذاتي'] },
  { ar: 'مساعد صعود المرتفعات', en: 'Hill Start Assist (HSA)', aliases: ['hsa', 'hill start assist', 'مساعد صعود المرتفعات'] },
  { ar: 'نزول المنحدرات', en: 'Hill Descent Control (HDC)', aliases: ['hdc', 'hill descent control', 'نزول المنحدرات'] },
  { ar: 'نظام مراقبة ضغط الإطارات', en: 'Tire Pressure Monitoring System (TPMS)', aliases: ['tpms', 'مراقبة ضغط الإطارات', 'tire pressure monitoring system'] },
  { ar: 'كاميرا خلفية', en: 'Rear View Camera', aliases: ['rear view camera', 'كاميرا خلفية'] },
  { ar: 'كاميرا 360 محيطية', en: '360° Surround View Camera', aliases: ['360° camera', '360 camera', 'كاميرات 360', 'كاميرا 360', 'كاميرا 360 درجة', '360° surround view camera'] },
  { ar: 'رؤية ليلية', en: 'Night Vision', aliases: ['night vision', 'رؤية ليلية'] },
  { ar: 'كشف المشاة', en: 'Pedestrian Detection', aliases: ['pedestrian detection', 'كشف المشاة'] },
  { ar: 'كشف الدراجات', en: 'Cyclist Detection', aliases: ['cyclist detection', 'كشف الدراجات'] },
  { ar: 'وسائد هوائية', en: 'Airbags', aliases: ['airbags', 'وسائد هوائية'] },
  { ar: 'وسائد هوائية أمامية', en: 'Front Airbags', aliases: ['front airbags', 'وسائد هوائية أمامية'] },
  { ar: 'وسائد جانبية', en: 'Side Airbags', aliases: ['side airbags', 'وسائد جانبية'] },
  { ar: 'وسائد ستائرية', en: 'Curtain Airbags', aliases: ['curtain airbags', 'وسائد ستائرية'] },
  { ar: 'وسادة ركبة', en: 'Knee Airbag', aliases: ['knee airbag', 'وسادة ركبة'] },
  { ar: 'وسادة هوائية وسطية', en: 'Center Airbag', aliases: ['center airbag', 'وسادة هوائية وسطية'] },
  { ar: 'ISOFIX', en: 'ISOFIX', aliases: ['isofix'] },
  
  // إضافات الأمان والسلامة الجديدة (New Safety Aids)
  { ar: 'مساعد تغيير الحارة النشط', en: 'Active Lane Change Assist', aliases: ['active lane change assist', 'مساعد تغيير الحارة النشط'] },
  { ar: 'مساعد التوجيه في حالات الطوارئ', en: 'Emergency Steering Assist', aliases: ['emergency steering assist', 'مساعد التوجيه في حالات الطوارئ'] },
  { ar: 'مساعد التوجيه التفادي لمنع الاصطدام', en: 'Evasive Steering Assist', aliases: ['evasive steering assist', 'مساعد التوجيه التفادي لمنع الاصطدام'] },
  { ar: 'تنبيه عند فتح الأبواب والخروج', en: 'Exit Warning', aliases: ['exit warning', 'تنبيه عند فتح الأبواب والخروج'] },
  { ar: 'مساعد الخروج الآمن', en: 'Safe Exit Assist', aliases: ['safe exit assist', 'مساعد الخروج الآمن'] },
  { ar: 'تنبيه حركة المرور الأمامية المتقاطعة', en: 'Front Cross Traffic Alert', aliases: ['front cross traffic alert', 'تنبيه حركة المرور الأمامية المتقاطعة'] },
  { ar: 'مساعد عبور التقاطعات والمنحنيات', en: 'Junction Assist', aliases: ['junction assist', 'مساعد عبور التقاطعات والمنحنيات'] },
  { ar: 'مساعد القيادة في الاختناقات المرورية', en: 'Traffic Jam Assist', aliases: ['traffic jam assist', 'مساعد القيادة في الاختناقات المرورية'] },
  { ar: 'مساعد القيادة على الطرق السريعة', en: 'Highway Assist', aliases: ['highway assist', 'مساعد القيادة على الطرق السريعة'] },
  { ar: 'مثبت السرعة الاستباقي الذكي', en: 'Predictive Cruise Control', aliases: ['predictive cruise control', 'مثبت السرعة الاستباقي الذكي'] },
  { ar: 'مساعد التحكم في المسافة الآمنة', en: 'Distance Control Assist', aliases: ['distance control assist', 'مساعد التحكم في المسافة الآمنة'] },
  { ar: 'مساعد التوقف التلقائي في حالات الطوارئ', en: 'Emergency Stop Assist', aliases: ['emergency stop assist', 'مساعد التوقف التلقائي في حالات الطوارئ'] },
  { ar: 'مراقبة خروج الركاب للتأمين', en: 'Occupant Exit Monitoring', aliases: ['occupant exit monitoring', 'مراقبة خروج الركاب للتأمين'] },
  { ar: 'نظام كشف وجود الأطفال داخل السيارة', en: 'Child Presence Detection', aliases: ['child presence detection', 'نظام كشف وجود الأطفال داخل السيارة'] },
  { ar: 'مساعد ثبات المقطورة والجر', en: 'Trailer Stability Assist', aliases: ['trailer stability assist', 'مساعد ثبات المقطورة والجر'] },
  { ar: 'مساعد التحكم في المقطورات', en: 'Trailer Assist', aliases: ['trailer assist', 'مساعد التحكم في المقطورات'] },
  { ar: 'مساعد الرجوع للخلف بالمقطورة', en: 'Trailer Reverse Assist', aliases: ['trailer reverse assist', 'مساعد الرجوع للخلف بالمقطورة'] },
  { ar: 'حساسات ركن محيطية 360 درجة', en: 'Surround Parking Sensors', aliases: ['surround parking sensors', 'حساسات ركن محيطية 360 درجة'] },
  { ar: 'حساسات ركن أمامية', en: 'Front Parking Sensors', aliases: ['front parking sensors', 'حساسات ركن أمامية'] },
  { ar: 'حساسات ركن خلفية', en: 'Rear Parking Sensors', aliases: ['rear parking sensors', 'حساسات ركن خلفية'] },
  { ar: 'عرض غطاء المحرك الشفاف لكشف الطريق', en: 'Transparent Hood View', aliases: ['transparent hood view', 'عرض غطاء المحرك الشفاف لكشف الطريق'] },
  { ar: 'كاميرا أسفل السيارة للطرق الوعرة', en: 'Underbody Camera', aliases: ['underbody camera', 'كاميرا أسفل السيارة للطرق الوعرة'] },
  { ar: 'كاميرا مراقبة المقطورة الخلفية', en: 'Trailer Camera', aliases: ['trailer camera', 'كاميرا مراقبة المقطورة الخلفية'] },

  // الراحة والتجهيزات (Comfort & Conveniences)
  { ar: 'دخول ذكي', en: 'Keyless Entry', aliases: ['keyless entry', 'دخول ذكي', 'دخول بدون مفتاح'] },
  { ar: 'تشغيل بدون مفتاح', en: 'Keyless Start', aliases: ['keyless start', 'تشغيل بدون مفتاح'] },
  { ar: 'تشغيل بالبصمة', en: 'Push Button Start', aliases: ['push button start', 'تشغيل بالبصمة', 'زر تشغيل المحرك'] },
  { ar: 'تشغيل عن بعد', en: 'Remote Start', aliases: ['remote start', 'تشغيل عن بعد'] },
  { ar: 'فتح وإغلاق عن بعد', en: 'Remote Access', aliases: ['remote access', 'فتح وإغلاق عن بعد'] },
  { ar: 'فرامل يد إلكترونية', en: 'Electronic Parking Brake (EPB)', aliases: ['epb', 'electronic parking brake', 'فرامل يد إلكترونية'] },
  { ar: 'تثبيت فرامل تلقائي', en: 'Auto Hold', aliases: ['auto hold', 'تثبيت فرامل تلقائي'] },
  { ar: 'غلق تلقائي للأبواب', en: 'Auto Door Lock', aliases: ['auto door lock', 'غلق تلقائي للأبواب'] },
  { ar: 'فتح الشنطة كهرباء', en: 'Power Tailgate', aliases: ['power tailgate', 'فتح الشنطة كهرباء', 'شنطة كهرباء'] },
  { ar: 'فتح الشنطة بالقدم', en: 'Hands-Free Tailgate', aliases: ['hands-free tailgate', 'فتح الشنطة بالقدم'] },
  { ar: 'شفط الأبواب', en: 'Soft Close Doors', aliases: ['soft close doors', 'شفط الأبواب'] },
  { ar: 'أبواب كهربائية', en: 'Power Doors', aliases: ['power doors', 'أبواب كهربائية'] },
  { ar: 'أبواب جانبية كهربائية انزلاقية', en: 'Power Sliding Doors', aliases: ['power sliding doors', 'أبواب جانبية كهربائية انزلاقية'] },
  { ar: 'مرايات كهرباء', en: 'Power Folding Mirrors', aliases: ['power folding mirrors', 'مرايات كهرباء', 'مرايا كهربائية'] },
  { ar: 'مرايات تسخين', en: 'Heated Mirrors', aliases: ['heated mirrors', 'مرايات تسخين'] },
  { ar: 'مرايات تعتيم تلقائي', en: 'Auto Dimming Mirrors', aliases: ['auto dimming mirrors', 'مرايات تعتيم تلقائي'] },
  { ar: 'مرايات ذاكرة', en: 'Memory Mirrors', aliases: ['memory mirrors', 'مرايات ذاكرة'] },
  { ar: 'مقاعد كهربائية', en: 'Power Seats', aliases: ['power seats', 'مقاعد كهربائية', 'كراسي كهرباء'] },
  { ar: 'ذاكرة المقاعد', en: 'Memory Seats', aliases: ['memory seats', 'ذاكرة المقاعد'] },
  { ar: 'تدفئة المقاعد', en: 'Heated Seats', aliases: ['heated seats', 'تدفئة المقاعد', 'تسخين كراسي'] },
  { ar: 'تبريد المقاعد', en: 'Ventilated Seats', aliases: ['ventilated seats', 'تبريد المقاعد', 'تبريد كراسي'] },
  { ar: 'مساج المقاعد', en: 'Massage Seats', aliases: ['massage seats', 'مساج المقاعد', 'كراسي مساج'] },
  { ar: 'دعم قطني', en: 'Lumbar Support', aliases: ['lumbar support', 'دعم قطني'] },
  { ar: 'مقاعد رياضية', en: 'Sport Seats', aliases: ['sport seats', 'مقاعد رياضية'] },
  { ar: 'مقاعد رياضية حاضنة', en: 'Bucket Seats', aliases: ['bucket seats', 'مقاعد رياضية حاضنة'] },
  { ar: 'تسخين المقاعد الخلفية', en: 'Rear Heated Seats', aliases: ['rear heated seats', 'تسخين المقاعد الخلفية'] },
  { ar: 'تبريد المقاعد الخلفية', en: 'Rear Ventilated Seats', aliases: ['rear ventilated seats', 'تبريد المقاعد الخلفية'] },
  { ar: 'تدفئة الدركسيون', en: 'Heated Steering Wheel', aliases: ['heated steering wheel', 'تدفئة الدركسيون'] },
  { ar: 'عجلة قيادة كهربائية', en: 'Power Steering Wheel', aliases: ['power steering wheel', 'عجلة قيادة كهربائية'] },
  { ar: 'عجلة قيادة بذاكرة', en: 'Memory Steering Wheel', aliases: ['memory steering wheel', 'عجلة قيادة بذاكرة'] },
  { ar: 'نظام تعطير الهواء المحيط', en: 'Ambient Air Package', aliases: ['ambient air package', 'نظام تعطير الهواء المحيط'] },
  { ar: 'تبريد حامل الأكواب', en: 'Cooled Cup Holders', aliases: ['cooled cup holders', 'تبريد حامل الأكواب'] },
  { ar: 'تبريد درج التابلوه', en: 'Cooled Glove Box', aliases: ['cooled glove box', 'تبريد درج التابلوه'] },

  // إضافات الراحة والتجهيزات الجديدة (New Comfort & Conveniences)
  { ar: 'فتح قفل السيارة التلقائي عند الاقتراب', en: 'Auto Unlock on Approach', aliases: ['auto unlock on approach', 'فتح قفل السيارة التلقائي عند الاقتراب'] },
  { ar: 'قفل السيارة التلقائي عند الابتعاد', en: 'Walk Away Auto Lock', aliases: ['walk away auto lock', 'قفل السيارة التلقائي عند الابتعاد'] },
  { ar: 'ميزة الدخول المريح وسهولة الركوب', en: 'Comfort Access', aliases: ['comfort access', 'ميزة الدخول المريح وسهولة الركوب'] },
  { ar: 'مساعد الدخول والخروج المريح', en: 'Easy Entry / Exit', aliases: ['easy entry / exit', 'مساعد الدخول والخروج المريح'] },
  { ar: 'وظيفة الترحيب بالمقعد وتحريكه للخلف', en: 'Welcome Seat Function', aliases: ['welcome seat function', 'وظيفة الترحيب بالمقعد وتحريكه للخلف'] },
  { ar: 'امتداد وسادة المقعد لدعم الفخذين', en: 'Seat Extension', aliases: ['seat extension', 'امتداد وسادة المقعد لدعم الفخذين'] },
  { ar: 'جوانب مقاعد قابلة للتعديل والتحكم', en: 'Adjustable Side Bolsters', aliases: ['adjustable side bolsters', 'جوانب مقاعد قابلة للتعديل والتحكم'] },
  { ar: 'تعديل ديناميكي نشط للمقعد مع المنعطفات', en: 'Dynamic Seat Adjustment', aliases: ['dynamic seat adjustment', 'تعديل ديناميكي نشط للمقعد مع المنعطفات'] },
  { ar: 'إمالة المقاعد الخلفية كهربائياً', en: 'Rear Seat Recline', aliases: ['rear seat recline', 'إمالة المقاعد الخلفية كهربائياً'] },
  { ar: 'مقاعد صالة رجال الأعمال الفاخرة بالخلف', en: 'Executive Lounge Seats', aliases: ['executive lounge seats', 'مقاعد صالة رجال الأعمال الفاخرة بالخلف'] },
  { ar: 'مقاعد كابتن منفصلة بالصف الثاني', en: 'Captain Seats', aliases: ['captain seats', 'مقاعد كابتن منفصلة بالصف الثاني'] },
  { ar: 'مقاعد خلفية قابلة للطي', en: 'Folding Rear Seats', aliases: ['folding rear seats', 'مقاعد خلفية قابلة للطي'] },
  { ar: 'مقاعد قابلة للطي بنسبة 60/40', en: 'Split Folding Seats', aliases: ['split folding seats', 'مقاعد قابلة للطي بنسبة 60/40'] },
  { ar: 'تحكم كهربائي بالمقاعد الخلفية', en: 'Power Rear Seats', aliases: ['power rear seats', 'تحكم كهربائي بالمقاعد الخلفية'] },
  { ar: 'تبريد وتهوية المقاعد الخلفية', en: 'Ventilated Rear Seats', aliases: ['ventilated rear seats', 'تبريد وتهوية المقاعد الخلفية'] },
  { ar: 'نظام مساج للمقاعد الخلفية', en: 'Rear Massage Seats', aliases: ['rear massage seats', 'نظام مساج للمقاعد الخلفية'] },
  { ar: 'تهوية مقاعد نشطة متكيفة', en: 'Active Seat Ventilation', aliases: ['active seat ventilation', 'تهوية مقاعد نشطة متكيفة'] },
  { ar: 'تدفئة الرقبة (أوشحة تدفئة هوائية)', en: 'Neck Heater', aliases: ['neck heater', 'تدفئة الرقبة (أوشحة تدفئة هوائية)'] },
  { ar: 'مساند ذراع مدفأة بالكامل', en: 'Heated Armrests', aliases: ['heated armrests', 'مساند ذراع مدفأة بالكامل'] },
  { ar: 'ألواح أبواب داخلية مدفأة', en: 'Heated Door Panels', aliases: ['heated door panels', 'ألواح أبواب داخلية مدفأة'] },
  { ar: 'حوامل أكواب بنظام تسخين', en: 'Heated Cup Holders', aliases: ['heated cup holders', 'حوامل أكواب بنظام تسخين'] },
  { ar: 'فتحات رشاشات مساحات مدفأة ضد التجمد', en: 'Heated Washer Nozzles', aliases: ['heated washer nozzles', 'فتحات رشاشات مساحات مدفأة ضد التجمد'] },
  { ar: 'طي التلقائي للمرايا عند القفل', en: 'Auto Folding Mirrors', aliases: ['auto folding mirrors', 'طي التلقائي للمرايا عند القفل'] },
  { ar: 'إمالة المرايا للأسفل عند الرجوع للخلف', en: 'Reverse Tilt Mirror', aliases: ['reverse tilt mirror', 'إمالة المرايا للأسفل عند الرجوع للخلف'] },
  { ar: 'أبواب بدون إطار زجاجي', en: 'Frameless Doors', aliases: ['frameless doors', 'أبواب بدون إطار زجاجي'] },
  { ar: 'أبواب شفط مريحة', en: 'Vacuum Doors', aliases: ['vacuum doors', 'أبواب شفط مريحة'] },

  // الشاشات والتكنولوجيا (Screens & Technology)
  { ar: 'عدادات رقمية', en: 'Digital Instrument Cluster', aliases: ['digital instrument cluster', 'عدادات رقمية', 'عدادات ديجيتال'] },
  { ar: 'العدادات الافتراضية الذكية', en: 'Virtual Cockpit', aliases: ['virtual cockpit', 'العدادات الافتراضية الذكية'] },
  { ar: 'شاشة معلومات وترفيه', en: 'Infotainment Display', aliases: ['infotainment display', 'infotainment screen', 'شاشة معلومات وترفيه', 'شاشة تعمل باللمس'] },
  { ar: 'شاشة راكب', en: 'Passenger Display', aliases: ['passenger display', 'شاشة راكب'] },
  { ar: 'شاشة خلفية', en: 'Rear Entertainment Screens', aliases: ['rear entertainment screen', 'rear entertainment screens', 'شاشة خلفية'] },
  { ar: 'عرض على الزجاج', en: 'Head-Up Display (HUD)', aliases: ['hud', 'head-up display', 'عرض على الزجاج', 'عرض المعلومات على الزجاج الأمامي'] },
  { ar: 'عرض المعلومات بالواقع المعزز', en: 'Augmented Reality Head-Up Display', aliases: ['augmented reality head-up display', 'عرض المعلومات بالواقع المعزز'] },
  { ar: 'شاحن لاسلكي', en: 'Wireless Charging', aliases: ['wireless charging', 'شاحن لاسلكي'] },
  { ar: 'أبل كاربلاي', en: 'Apple CarPlay', aliases: ['apple carplay', 'أبل كاربلاي', 'أبل كار بلاي'] },
  { ar: 'أندرويد أوتو', en: 'Android Auto', aliases: ['android auto', 'أندرويد أوتو'] },
  { ar: 'أبل كاربلاي لاسلكي', en: 'Wireless Apple CarPlay', aliases: ['wireless apple carplay', 'أبل كاربلاي لاسلكي'] },
  { ar: 'أندرويد أوتو لاسلكي', en: 'Wireless Android Auto', aliases: ['wireless android auto', 'أندرويد أوتو لاسلكي'] },
  { ar: 'أوامر صوتية', en: 'Voice Control', aliases: ['voice control', 'أوامر صوتية'] },
  { ar: 'مساعد ذكي', en: 'AI Assistant', aliases: ['ai assistant', 'مساعد ذكي'] },
  { ar: 'نظام ملاحة', en: 'Navigation System (GPS)', aliases: ['gps', 'navigation system', 'نظام ملاحة'] },
  { ar: 'تحديثات عبر الإنترنت', en: 'Over-the-Air Updates (OTA)', aliases: ['ota', 'over-the-air updates', 'تحديثات عبر الإنترنت'] },
  { ar: 'واي فاي داخلي', en: 'In-Car Wi-Fi', aliases: ['in-car wifi', 'in-car wi-fi', 'wifi', 'واي فاي داخلي'] },
  { ar: 'نقاط USB-C', en: 'USB-C Ports', aliases: ['usb-c ports', 'usb-c', 'نقاط usb-c'] },
  { ar: 'كاميرا تسجيل', en: 'Dash Cam', aliases: ['dash cam', 'كاميرا تسجيل'] },
  { ar: 'مفتاح رقمي', en: 'Digital Key', aliases: ['digital key', 'مفتاح رقمي'] },
  { ar: 'مفتاح الاتصال قريب المدى NFC', en: 'NFC Key', aliases: ['nfc key', 'مفتاح الاتصال قريب المدى nfc'] },
  { ar: 'تكامل الهاتف الذكي', en: 'Smartphone Integration', aliases: ['smartphone integration', 'تكامل الهاتف الذكي'] },
  { ar: 'الخدمات المتصلة', en: 'Connected Services', aliases: ['connected services', 'الخدمات المتصلة'] },
  { ar: 'التحكم بالمركبة عن بعد', en: 'Remote Vehicle Control', aliases: ['remote vehicle control', 'التحكم بالمركبة عن بعد'] },
  { ar: 'التحكم بالإيماءات وحركات اليد', en: 'Gesture Control', aliases: ['gesture control', 'التحكم بالإيماءات وحركات اليد'] },
  { ar: 'مرآة خلفية رقمية بكاميرا', en: 'Digital Rear View Mirror', aliases: ['digital rear view mirror', 'مرآة خلفية رقمية بكاميرا'] },

  // إضافات الشاشات والتكنولوجيا الجديدة (New Tech & Display)
  { ar: 'شاشة عرض منحنية فائقة الدقة', en: 'Curved Display', aliases: ['curved display', 'شاشة عرض منحنية فائقة الدقة'] },
  { ar: 'شاشات بتقنية OLED عالية التباين', en: 'OLED Display', aliases: ['oled display', 'شاشات بتقنية oled عالية التباين'] },
  { ar: 'شاشات عرض شفافة مبتكرة', en: 'Transparent Display', aliases: ['transparent display', 'شاشات عرض شفافة مبتكرة'] },
  { ar: 'شاشة ترفيهية خاصة بالراكب الأمامي', en: 'Passenger Entertainment Display', aliases: ['passenger entertainment display', 'شاشة ترفيهية خاصة بالراكب الأمامي'] },
  { ar: 'نظام ترفيهي لركاب المقاعد الخلفية', en: 'Rear Seat Entertainment', aliases: ['rear seat entertainment', 'نظام ترفيهي لركاب المقاعد الخلفية'] },
  { ar: 'دمج خدمات البث الترفيهي (نتفليكس، يوتيوب)', en: 'Streaming Services Integration', aliases: ['streaming services integration', 'دمج خدمات البث الترفيهي'] },
  { ar: 'تطبيقات مدمجة بنظام السيارة الذكي', en: 'Built-in Apps', aliases: ['built-in apps', 'تطبيقات مدمجة بنظام السيارة الذكي'] },
  { ar: 'مزامنة ملفات المستخدم السحابية', en: 'Cloud Profile Sync', aliases: ['cloud profile sync', 'مزامنة ملفات المستخدم السحابية'] },
  { ar: 'ملفات تعريف متعددة للمستخدمين بالذاكرة', en: 'Multiple User Profiles', aliases: ['multiple user profiles', 'ملفات تعريف متعددة للمستخدمين بالذاكرة'] },
  { ar: 'نظام التعرف على ملامح الوجه للتشغيل والأمان', en: 'Face Recognition', aliases: ['face recognition', 'نظام التعرف على ملامح الوجه'] },
  { ar: 'تحديد هوية السائق وضبط إعداداته تلقائياً', en: 'Driver Identification', aliases: ['driver identification', 'تحديد هوية السائق وضبط إعداداته تلقائياً'] },
  { ar: 'نظام البصمة لتشغيل السيارة وحفظ الإعدادات', en: 'Fingerprint Authentication', aliases: ['fingerprint authentication', 'نظام البصمة لتشغيل السيارة'] },
  { ar: 'نظام الدخول بالقياسات الحيوية (الوجه/البصمة)', en: 'Biometric Access', aliases: ['biometric access', 'نظام الدخول بالقياسات الحيوية'] },
  { ar: 'تكامل كامل وشامل بين الهاتف والسيارة', en: 'Vehicle-to-Phone Integration', aliases: ['vehicle-to-phone integration', 'تكامل كامل وشامل بين الهاتف والسيارة'] },
  { ar: 'تكامل السيارة مع المنزل الذكي', en: 'Vehicle-to-Home Integration', aliases: ['vehicle-to-home integration', 'تكامل السيارة مع المنزل الذكي'] },
  { ar: 'ميزة تزويد الأجهزة الخارجية بالطاقة V2L', en: 'Vehicle-to-Load (V2L)', aliases: ['vehicle-to-load', 'v2l', 'vehicle-to-load (v2l)'] },
  { ar: 'اتصال المركبة بالمركبات الأخرى V2V', en: 'Vehicle-to-Vehicle Communication (V2V)', aliases: ['v2v', 'vehicle-to-vehicle communication', 'vehicle-to-vehicle communication (v2v)'] },
  { ar: 'اتصال المركبة بالبنية التحتية للطرق V2I', en: 'Vehicle-to-Infrastructure (V2I)', aliases: ['v2i', 'vehicle-to-infrastructure', 'vehicle-to-infrastructure (v2i)'] },
  { ar: 'شريحة اتصال إلكترونية مدمجة eSIM', en: 'eSIM Connectivity', aliases: ['esim connectivity', 'esim', 'شريحة اتصال إلكترونية مدمجة esim'] },
  { ar: 'اتصال مباشر بالأقمار الصناعية للطوارئ', en: 'Satellite Connectivity', aliases: ['satellite connectivity', 'اتصال مباشر بالأقمار الصناعية للطوارئ'] },
  { ar: 'كتيب دليل المالك الرقمي المدمج بالشاشة', en: 'Digital Owner Manual', aliases: ['digital owner manual', 'كتيب دليل المالك الرقمي المدمج بالشاشة'] },
  { ar: 'مسجل بيانات الحوادث والأحداث (الصندوق الأسود)', en: 'Event Data Recorder', aliases: ['event data recorder', 'مسجل بيانات الحوادث والأحداث'] },
  { ar: 'خدمات الملاحة وتحديثات المرور الحية', en: 'Live Traffic Services', aliases: ['live traffic services', 'خدمات الملاحة وتحديثات المرور الحية'] },
  { ar: 'نظام الركن الذكي والتحكم بالمفتاح عن بعد', en: 'Remote Parking', aliases: ['remote parking', 'نظام الركن الذكي والتحكم بالمفتاح عن بعد'] },
  { ar: 'وضعية استدعاء السيارة عن بعد Summon', en: 'Summon Mode', aliases: ['summon mode', 'وضعية استدعاء السيارة عن بعد summon'] },
  { ar: 'الاستدعاء الذكي للسيارة من المواقف المزدحمة', en: 'Smart Summon', aliases: ['smart summon', 'الاستدعاء الذكي للسيارة من المواقف المزدحمة'] },
  { ar: 'تشغيل مكيف السيارة وتدفئة المقاعد عن بعد', en: 'Remote Climate Control', aliases: ['remote climate control', 'تشغيل مكيف السيارة وتدفئة المقاعد عن بعد'] },
  { ar: 'تهيئة درجة حرارة الكابينة مسبقاً', en: 'Cabin Preconditioning', aliases: ['cabin preconditioning', 'تهيئة درجة حرارة الكابينة مسبقاً'] },

  // الإضاءة (Lighting)
  { ar: 'مصابيح LED', en: 'LED Headlights', aliases: ['led headlights', 'مصابيح led', 'إضاءة زينون / ليد'] },
  { ar: 'مصابيح Matrix', en: 'Matrix LED Headlights', aliases: ['matrix led', 'matrix led headlights', 'مصابيح matrix'] },
  { ar: 'مصابيح ليزر', en: 'Laser Headlights', aliases: ['laser headlights', 'مصابيح ليزر'] },
  { ar: 'إضاءة متكيفة', en: 'Adaptive Headlights', aliases: ['adaptive headlights', 'إضاءة متكيفة'] },
  { ar: 'مساعد الضوء العالي المتكيف', en: 'Adaptive High Beam Assist', aliases: ['adaptive high beam assist', 'مساعد الضوء العالي المتكيف'] },
  { ar: 'إضاءة عادية وعالية تلقائية', en: 'Automatic High Beam', aliases: ['automatic high beam', 'إضاءة عادية وعالية تلقائية'] },
  { ar: 'إضاءة نهارية', en: 'Daytime Running Lights (DRL)', aliases: ['drl', 'daytime running lights', 'إضاءة نهارية'] },
  { ar: 'إشارات متحركة', en: 'Dynamic Turn Signals', aliases: ['dynamic turn signals', 'إشارات متحركة'] },
  { ar: 'إضاءة ترحيبية', en: 'Welcome Lights', aliases: ['welcome lights', 'إضاءة ترحيبية'] },
  { ar: 'إضاءة محيطية', en: 'Ambient Lighting', aliases: ['ambient lighting', 'إضاءة محيطية'] },
  { ar: 'إضاءة داخلية متعددة الألوان', en: 'Multi-Color Ambient Lighting', aliases: ['multi color ambient', 'multi-color ambient lighting', 'إضاءة داخلية متعددة الألوان'] },
  { ar: 'إضاءة شعار', en: 'Logo Projection Lights', aliases: ['logo projection', 'logo projection lights', 'إضاءة شعار'] },
  { ar: 'إضاءة المنعطفات', en: 'Cornering Lights', aliases: ['cornering lights', 'إضاءة المنعطفات'] },

  // إضافات الإضاءة الجديدة (New Lighting Options)
  { ar: 'مصابيح بكسل ليد الرقمية الفائقة Pixel LED', en: 'Pixel LED Headlights', aliases: ['pixel led', 'pixel led headlights', 'مصابيح بكسل ليد الرقمية الفائقة'] },
  { ar: 'مصابيح خلفية بتقنية OLED ثلاثية الأبعاد', en: 'OLED Tail Lights', aliases: ['oled tail lights', 'مصابيح خلفية بتقنية oled ثلاثية الأبعاد'] },
  { ar: 'تقنية الإضاءة الرقمية فائقة الوضوح والبروجكتر', en: 'Digital Light', aliases: ['digital light', 'تقنية الإضاءة الرقمية فائقة الوضوح والبروجكتر'] },
  { ar: 'تأثيرات إضاءة متحركة وترحيبية', en: 'Animated Lighting', aliases: ['animated lighting', 'تأثيرات إضاءة متحركة وترحيبية'] },
  { ar: 'إشارات انعطاف تتابعية متحركة', en: 'Sequential Indicators', aliases: ['sequential indicators', 'إشارات انعطاف تتابعية متحركة'] },
  { ar: 'عرض متحرك ترحيبي بالأنوار الخارجية', en: 'Welcome Animation', aliases: ['welcome animation', 'عرض متحرك ترحيبي بالأنوار الخارجية'] },
  { ar: 'عرض متحرك وداعي بالأنوار الخارجية', en: 'Goodbye Animation', aliases: ['goodbye animation', 'عرض متحرك وداعي بالأنوار الخارجية'] },
  { ar: 'أضواء فرامل طوارئ متكيفة سريعة الوميض', en: 'Adaptive Brake Lights', aliases: ['adaptive brake lights', 'أضواء فرامل طوارئ متكيفة سريعة الوميض'] },
  { ar: 'مساعد الإضاءة الديناميكي لمنع إبهار الآخرين', en: 'Dynamic Light Assist', aliases: ['dynamic light assist', 'مساعد الإضاءة الديناميكي لمنع إبهار الآخرين'] },
  { ar: 'إضاءة جانبية إضافية عند الانعطاف', en: 'Corner Illumination', aliases: ['corner illumination', 'إضاءة جانبية إضافية عند الانعطاف'] },
  { ar: 'إضاءة ترحيبية أسفل الأبواب وعلى الأرض', en: 'Puddle Lamps', aliases: ['puddle lamps', 'إضاءة ترحيبية أسفل الأبواب وعلى الأرض'] },

  // السقف والزجاج (Roof & Glass)
  { ar: 'فتحة سقف', en: 'Sunroof', aliases: ['sunroof', 'فتحة سقف'] },
  { ar: 'فتحة سقف بانوراما', en: 'Panoramic Sunroof', aliases: ['panoramic sunroof', 'بانوراما', 'فتحة سقف بانوراما'] },
  { ar: 'سقف زجاجي بانورامي ثابت', en: 'Panoramic Glass Roof', aliases: ['panoramic glass roof', 'سقف زجاجي بانورامي ثابت'] },
  { ar: 'سقف زجاجي ثابت', en: 'Fixed Glass Roof', aliases: ['fixed glass roof', 'سقف زجاجي ثابت'] },
  { ar: 'فتحة سقف كهربائية', en: 'Power Sunroof', aliases: ['power sunroof', 'فتحة سقف كهربائية'] },
  { ar: 'سقف كهربائي قماشي', en: 'Convertible Roof', aliases: ['convertible roof', 'سقف كهربائي قماشي'] },
  { ar: 'سقف إلكتروكرومي ذكي متغير التظليل', en: 'Electrochromic Roof', aliases: ['electrochromic roof', 'سقف إلكتروكرومي ذكي متغير التظليل'] },
  { ar: 'زجاج عازل', en: 'Acoustic Glass', aliases: ['acoustic glass', 'زجاج عازل'] },
  { ar: 'زجاج مزدوج', en: 'Double Glazed Glass', aliases: ['double glazed glass', 'زجاج مزدوج'] },
  { ar: 'زجاج خلفية مظلل', en: 'Privacy Glass', aliases: ['privacy glass', 'زجاج خلفية مظلل', 'زجاج فاميه'] },
  { ar: 'زجاج أمامي بنظام تدفئة لإزالة الصقيع', en: 'Heated Windshield', aliases: ['heated windshield', 'زجاج أمامي بنظام تدفئة لإزالة الصقيع'] },
  { ar: 'مساحات بمستشعر المطر تلقائية', en: 'Rain Sensing Wipers', aliases: ['rain sensing wipers', 'مساحات بمستشعر المطر تلقائية'] },

  // إضافات السقف والزجاج الجديدة (New Roof & Glass Options)
  { ar: 'طلاء خارجي ذكي معالج للخدوش البسيطة ذاتياً', en: 'Self Healing Paint', aliases: ['self healing paint', 'طلاء خارجي ذكي معالج للخدوش البسيطة ذاتياً'] },
  { ar: 'باقة الطلاء الخارجي المطفي المميز Matte Paint', en: 'Matte Paint Package', aliases: ['matte paint package', 'باقة الطلاء الخارجي المطفي المميز matte paint'] },
  { ar: 'سقف السيارة الخارجي باللون الأسود اللامع', en: 'Black Roof', aliases: ['black roof', 'سقف السيارة الخارجي باللون الأسود اللامع'] },
  { ar: 'سقف سيارة رياضي مصنوع من ألياف الكربون', en: 'Carbon Roof', aliases: ['carbon roof', 'سقف سيارة رياضي مصنوع من ألياف الكربون'] },
  { ar: 'غطاء محرك نشط للحماية وامتصاص الصدمات', en: 'Active Hood', aliases: ['active hood', 'غطاء محرك نشط للحماية وامتصاص الصدمات'] },
  { ar: 'غطاء صندوق أمتعة أمامي كهربائي بالكامل', en: 'Powered Frunk', aliases: ['powered frunk', 'غطاء صندوق أمتعة أمامي كهربائي بالكامل'] },
  { ar: 'قفل وشفط صندوق الأمتعة الخلفي ناعم الملمس', en: 'Soft Close Trunk', aliases: ['soft close trunk', 'قفل وشفط صندوق الأمتعة الخلفي ناعم الملمس'] },
  { ar: 'صندوق أمتعة أمامي يفتح ويغلق كهربائياً Frunk', en: 'Power Frunk', aliases: ['power frunk', 'صندوق أمتعة أمامي يفتح ويغلق كهربائياً frunk'] },
  { ar: 'زجاج أمامي بنظام عزل صوتي إضافي مضاعف', en: 'Acoustic Windshield', aliases: ['acoustic windshield', 'زجاج أمامي بنظام عزل صوتي إضافي مضاعف'] },
  { ar: 'زجاج خلفي مدفأ لإزالة الصقيع وضباب الطريق', en: 'Heated Rear Window', aliases: ['heated rear window', 'زجاج خلفي مدفأ لإزالة الصقيع وضباب الطريق'] },
  { ar: 'زجاج عازل وواقٍ من الأشعة فوق البنفسجية', en: 'UV Protection Glass', aliases: ['uv protection glass', 'زجاج عازل وواقٍ من الأشعة فوق البنفسجية'] },
  { ar: 'زجاج تظليل ذكي يتغير أوتوماتيكياً', en: 'Smart Tint Glass', aliases: ['smart tint glass', 'زجاج تظليل ذكي يتغير أوتوماتيكياً'] },
  { ar: 'نوافذ إلكتروكرومية ذكية متغيرة التعتيم', en: 'Electrochromic Windows', aliases: ['electrochromic windows', 'نوافذ إلكتروكرومية ذكية متغيرة التعتيم'] },

  // الأداء والقيادة (Performance & Driving)
  { ar: 'أوضاع قيادة', en: 'Drive Modes', aliases: ['drive modes', 'أوضاع قيادة', 'أنظمة قيادة متعددة'] },
  { ar: 'تعليق متكيف', en: 'Adaptive Suspension', aliases: ['adaptive suspension', 'تعليق متكيف'] },
  { ar: 'تعليق هوائي', en: 'Air Suspension', aliases: ['air suspension', 'تعليق هوائي'] },
  { ar: 'نظام تعليق نشط', en: 'Active Suspension', aliases: ['active suspension', 'نظام تعليق نشط'] },
  { ar: 'توجيه خلفي', en: 'Rear Wheel Steering', aliases: ['rear wheel steering', 'توجيه خلفي'] },
  { ar: 'نظام دفع رباعي', en: 'All Wheel Drive (AWD)', aliases: ['awd', 'all wheel drive', 'نظام دفع رباعي'] },
  { ar: 'نظام دفع رباعي مستمر 4WD', en: 'Four Wheel Drive (4WD)', aliases: ['4wd', 'four wheel drive', 'نظام دفع رباعي مستمر 4wd'] },
  { ar: 'توجيه وتوزيع عزم الدوران', en: 'Torque Vectoring', aliases: ['torque vectoring', 'توجيه وتوزيع عزم الدوران'] },
  { ar: 'لانش كنترول', en: 'Launch Control', aliases: ['launch control', 'لانش كنترول'] },
  { ar: 'قفل دفرنس', en: 'Differential Lock', aliases: ['differential lock', 'قفل دفرنس'] },
  { ar: 'ترس تفاضلي إلكتروني', en: 'Electronic Differential', aliases: ['electronic differential', 'ترس تفاضلي إلكتروني'] },
  { ar: 'ترس تفاضلي رياضي لزيادة الثبات', en: 'Sport Differential', aliases: ['sport differential', 'ترس تفاضلي رياضي لزيادة الثبات'] },
  { ar: 'عادم رياضي', en: 'Sport Exhaust', aliases: ['sport exhaust', 'عادم رياضي'] },
  { ar: 'نظام إيقاف وتشغيل', en: 'Start / Stop System', aliases: ['start / stop system', 'نظام إيقاف وتشغيل', 'start / stop'] },
  { ar: 'محدد التروس الدوار / ناقل الحركة الذكي', en: 'Drive Selector', aliases: ['drive selector', 'محدد التروس الدوار / ناقل الحركة الذكي'] },
  { ar: 'نظام الديناميكا الهوائية النشط', en: 'Active Aerodynamics', aliases: ['active aerodynamics', 'نظام الديناميكا الهوائية النشط'] },
  { ar: 'سبويلر خلفي نشط متحرك', en: 'Active Spoiler', aliases: ['active spoiler', 'سبويلر خلفي نشط متحرك'] },
  { ar: 'قيادة شبه ذاتية', en: 'Semi-Autonomous Driving', aliases: ['semi-autonomous driving', 'semi autonomous driving', 'قيادة شبه ذاتية'] },
  { ar: 'قيادة ذاتية', en: 'Autonomous Driving', aliases: ['autonomous driving', 'قيادة ذاتية'] },
  { ar: 'مسجل بيانات الأداء الرياضي', en: 'Performance Data Recorder', aliases: ['performance data recorder', 'مسجل بيانات الأداء الرياضي'] },

  // إضافات الأداء والقيادة الجديدة (New Driving Performance Aids)
  { ar: 'قواعد محرك نشطة ديناميكية لتقليل الاهتزازات', en: 'Active Engine Mounts', aliases: ['active engine mounts', 'قواعد محرك نشطة ديناميكية لتقليل الاهتزازات'] },
  { ar: 'نظام التحكم الديناميكي بالشاسيه والاتزان DCC', en: 'Dynamic Chassis Control', aliases: ['dynamic chassis control', 'dcc', 'نظام التحكم الديناميكي بالشاسيه والاتزان'] },
  { ar: 'نظام تعليق استباقي يقرأ عيوب الطريق مسبقاً', en: 'Predictive Suspension', aliases: ['predictive suspension', 'نظام تعليق استباقي يقرأ عيوب الطريق مسبقاً'] },
  { ar: 'تحكم إلكتروني متكامل بالمساعدين وقوة الدعم EDC', en: 'Electronic Damper Control', aliases: ['electronic damper control', 'edc', 'تحكم إلكتروني متكامل بالمساعدين وقوة الدعم'] },
  { ar: 'نظام التعليق الهوائي المتطور متكيف الارتفاع ABC', en: 'Air Body Control', aliases: ['air body control', 'abc', 'نظام التعليق الهوائي المتطور متكيف الارتفاع'] },
  { ar: 'نظام منع تدحرج وجنوح الهيكل النشط بالمنعطفات', en: 'Active Roll Stabilization', aliases: ['active roll stabilization', 'نظام منع تدحرج وجنوح الهيكل النشط بالمنعطفات'] },
  { ar: 'ترس تفاضلي خلفي ذكي متطور', en: 'Rear Differential', aliases: ['rear differential', 'ترس تفاضلي خلفي ذكي متطور'] },
  { ar: 'وضعية الانجراف والتفحيط الرياضية المحكمة Drift Mode', en: 'Drift Mode', aliases: ['drift mode', 'وضعية الانجراف والتفحيط الرياضية المحكمة'] },
  { ar: 'وضعية الحلبات والسباقات القصوى Race Mode', en: 'Race Mode', aliases: ['race mode', 'وضعية الحلبات والسباقات القصوى'] },
  { ar: 'وضعية القيادة على الطرق الوعرة والرمال الصعبة', en: 'Off-Road Mode', aliases: ['off-road mode', 'off road mode', 'وضعية القيادة على الطرق الوعرة والرمال الصعبة'] },
  { ar: 'وضعية القيادة الآمنة على الثلوج والجليد', en: 'Snow Mode', aliases: ['snow mode', 'وضعية القيادة الآمنة على الثلوج والجليد'] },
  { ar: 'وضعية القيادة للرمال والصحاري الصعبة', en: 'Sand Mode', aliases: ['sand mode', 'وضعية القيادة للرمال والصحاري الصعبة'] },
  { ar: 'وضعية القيادة المخصصة بالكامل للسائق Individual', en: 'Individual Mode', aliases: ['individual mode', 'individual', 'وضعية القيادة المخصصة بالكامل للسائق'] },
  { ar: 'وضعية المضمار والتسارع الرياضي الدقيق Track Mode', en: 'Track Mode', aliases: ['track mode', 'وضعية المضمار والتسارع الرياضي الدقيق'] },
  { ar: 'موزع عزم الدوران الذكي بين العجلات', en: 'Torque Splitter', aliases: ['torque splitter', 'موزع عزم الدوران الذكي بين العجلات'] },
  { ar: 'مساعد التسارع الذكي والانطلاق Launch Assist', en: 'Launch Assist', aliases: ['launch assist', 'مساعد التسارع الذكي والانطلاق'] },
  { ar: 'القيادة بدواسة واحدة للتسارع والكبح التلقائي', en: 'One Pedal Driving', aliases: ['one pedal driving', 'القيادة بدواسة واحدة للتسارع والكبح التلقائي'] },
  { ar: 'فرامل استعادة الطاقة وإعادة شحن البطارية', en: 'Regenerative Braking', aliases: ['regenerative braking', 'فرامل استعادة الطاقة وإعادة شحن البطارية'] },
  { ar: 'استعادة طاقة الكبح لشحن بطاريات السيارة', en: 'Brake Energy Recovery', aliases: ['brake energy recovery', 'استعادة طاقة الكبح لشحن بطاريات السيارة'] },
  { ar: 'نظام رفع السيارة الهيدروليكي للمطبات والارتفاع', en: 'Lift System', aliases: ['lift system', 'نظام رفع السيارة الهيدروليكي'] },
  { ar: 'نظام رفع المحور الأمامي لتفادي المطبات والصخور', en: 'Front Axle Lift', aliases: ['front axle lift', 'نظام رفع المحور الأمامي'] },
  { ar: 'نظام رفع المحور الخلفي لتفادي الاحتكاك', en: 'Rear Axle Lift', aliases: ['rear axle lift', 'نظام رفع المحور الخلفي'] },
  { ar: 'صمامات عادم نشطة ذكية لتغيير نغمة الصوت الصوتية', en: 'Active Exhaust Valves', aliases: ['active exhaust valves', 'صمامات عادم نشطة ذكية'] },

  // التكييف والهواء (Climate & Air)
  { ar: 'تكييف ثنائي المناطق', en: 'Dual Zone Climate Control', aliases: ['dual zone climate control', 'تكييف ثنائي المناطق'] },
  { ar: 'تكييف ثلاثي المناطق مستقل', en: 'Three Zone Climate Control', aliases: ['three zone climate control', 'تكييف ثلاثي المناطق مستقل'] },
  { ar: 'أربع مناطق تكييف مستقلة', en: 'Four Zone Climate Control', aliases: ['four zone climate control', 'four zone climate', 'أربع مناطق تكييف', 'أربع مناطق تكييف مستقلة'] },
  { ar: 'تبريد خلفي مستقل', en: 'Rear Climate Control', aliases: ['rear climate control', 'تبريد خلفي مستقل'] },
  { ar: 'تنقية الهواء', en: 'Air Purification System', aliases: ['air purification system', 'تنقية الهواء'] },
  { ar: 'معطر تكييف داخلي ذكي', en: 'Fragrance System', aliases: ['fragrance system', 'معطر تكييف داخلي ذكي'] },
  { ar: 'نظام تأيين وتنقية الهواء', en: 'Ionizer', aliases: ['ionizer', 'نظام تأيين وتنقية الهواء'] },

  // إضافات التكييف والهواء الجديدة (New Climate Options)
  { ar: 'فلتر هيبا فائق الجودة والتعقيم HEPA Filter', en: 'HEPA Filter', aliases: ['hepa filter', 'hepa', 'فلتر هيبا فائق الجودة والتعقيم'] },
  { ar: 'نظام العلاج العطري الطبيعي المدمج بالسيارة', en: 'Aromatherapy System', aliases: ['aromatherapy system', 'نظام العلاج العطري الطبيعي المدمج بالسيارة'] },
  { ar: 'نظام تعطير الكابينة بروائح مخصصة فاخرة', en: 'Cabin Scent System', aliases: ['cabin scent system', 'نظام تعطير الكابينة بروائح مخصصة فاخرة'] },
  { ar: 'نظام المراقبة المستمرة لجودة ونقاء الهواء', en: 'Air Quality Monitoring', aliases: ['air quality monitoring', 'نظام المراقبة المستمرة لجودة ونقاء الهواء'] },
  { ar: 'فلتر جزيئات هواء فائق الصغر والكفاءة PM2.5', en: 'PM2.5 Filter', aliases: ['pm2.5 filter', 'pm2.5', 'فلتر جزيئات هواء فائق الصغر والكفاءة'] },
  { ar: 'نظام تعقيم الهواء بالأشعة فوق البنفسجية من البكتيريا', en: 'UV Air Sterilization', aliases: ['uv air sterilization', 'نظام تعقيم الهواء بالأشعة فوق البنفسجية'] },

  // الفخامة والداخلية (Luxury & Interior)
  { ar: 'نظام صوتي ممتاز', en: 'Premium Sound System', aliases: ['premium sound system', 'نظام صوت فاخر', 'نظام صوتي ممتاز'] },
  { ar: 'صوت ثلاثي الأبعاد', en: '3D Surround Sound', aliases: ['3d surround sound', 'صوت ثلاثي الأبعاد'] },
  { ar: 'عزل الضوضاء النشط للهدوء', en: 'Noise Cancellation', aliases: ['noise cancellation', 'عزل الضوضاء النشط للهدوء'] },
  { ar: 'جلد نابا', en: 'Nappa Leather', aliases: ['nappa leather', 'جلد نابا'] },
  { ar: 'ألكانتارا', en: 'Alcantara Interior', aliases: ['alcantara', 'alcantara interior', 'ألكانتارا'] },
  { ar: 'تطعيم خشب', en: 'Wood Trim', aliases: ['wood trim', 'تطعيم خشب'] },
  { ar: 'تطعيم كربون', en: 'Carbon Fiber Trim', aliases: ['carbon fiber trim', 'تطعيم كربون'] },
  { ar: 'عتبات أبواب مضيئة بشعار السيارة', en: 'Illuminated Door Sills', aliases: ['illuminated door sills', 'عتبات أبواب مضيئة بشعار السيارة'] },
  { ar: 'ثلاجة', en: 'Refrigerator', aliases: ['refrigerator', 'ثلاجة'] },
  { ar: 'مقاعد خلفية فاخرة لرجال الأعمال', en: 'Executive Rear Seats', aliases: ['executive rear seats', 'مقاعد خلفية فاخرة لرجال الأعمال'] },
  { ar: 'مقاعد خلفية مريحة مع مسند أقدام Ottoman', en: 'Rear Ottoman Seats', aliases: ['rear ottoman seats', 'مقاعد خلفية مريحة مع مسند أقدام ottoman'] },
  { ar: 'سقف نجوم', en: 'Starlight Headliner', aliases: ['starlight headliner', 'سقف نجوم'] },
  { ar: 'تابلت خلفي للتحكم بالأنظمة والترفيه', en: 'Rear Tablet Controls', aliases: ['rear tablet controls', 'تابلت خلفي للتحكم بالأنظمة والترفيه'] },
  { ar: 'الباقة التنفيذية الفاخرة للمقاعد الخلفية', en: 'Rear Executive Package', aliases: ['rear executive package', 'الباقة التنفيذية الفاخرة للمقاعد الخلفية'] },
  { ar: 'باقة الخصوصية والستائر الجانبية', en: 'Privacy Package', aliases: ['privacy package', 'باقة الخصوصية والستائر الجانبية'] },
  { ar: 'باقة السائق الخاصة بالفخامة', en: 'Chauffeur Package', aliases: ['chauffeur package', 'باقة السائق الخاصة بالفخامة'] },

  // إضافات الفخامة والداخلية الجديدة (New Luxury & Interior Options)
  { ar: 'نظام حجب وإلغاء الضوضاء الخارجية النشط', en: 'Active Noise Cancellation', aliases: ['active noise cancellation', 'نظام حجب وإلغاء الضوضاء الخارجية النشط'] },
  { ar: 'باقة الراحة الصوتية والعزل الكامل المتطور', en: 'Acoustic Comfort Package', aliases: ['acoustic comfort package', 'باقة الراحة الصوتية والعزل الكامل المتطور'] },
  { ar: 'عزل صوتي مزدوج للأبواب والزجاج لراحة كاملة', en: 'Double Insulation', aliases: ['double insulation', 'عزل صوتي مزدوج للأبواب والزجاج لراحة كاملة'] },

  // الباقات (Packages)
  { ar: 'باقة الفخامة', en: 'Luxury Package', aliases: ['luxury package', 'باقة الفخامة'] },
  { ar: 'الباقة الرياضية', en: 'Sport Package', aliases: ['sport package', 'الباقة الرياضية'] },
  { ar: 'باقة إس لاين الرياضية من أودي S-Line', en: 'S Line Package', aliases: ['s line package', 's-line', 'باقة إس لاين الرياضية من أودي s-line'] },
  { ar: 'باقة إم سبورت الرياضية من بي إم دبليو M Sport', en: 'M Sport Package', aliases: ['m sport package', 'm sport', 'باقة إم سبورت الرياضية من بي إم دبليو m sport'] },
  { ar: 'باقة إيه إم جي الرياضية من مرسيدس AMG', en: 'AMG Package', aliases: ['amg package', 'amg', 'باقة إيه إم جي الرياضية من مرسيدس amg'] },
  { ar: 'الباقة السوداء الرياضية الكاملة للسيارة Black Optics', en: 'Black Optics Package', aliases: ['black optics package', 'black optics', 'الباقة السوداء الرياضية الكاملة للسيارة black optics'] },
  { ar: 'باقة ألياف الكربون الخارجية والداخلية Carbon Fiber', en: 'Carbon Package', aliases: ['carbon package', 'carbon fiber package', 'باقة ألياف الكربون الخارجية والداخلية carbon fiber'] },
  { ar: 'باقة الطرق الوعرة والرمال والارتفاع', en: 'Off-Road Package', aliases: ['off-road package', 'off road package', 'باقة الطرق الوعرة والرمال والارتفاع'] },
  { ar: 'باقة سحب المقطورات والجر', en: 'Towing Package', aliases: ['towing package', 'باقة سحب المقطورات والجر'] },
  { ar: 'باقة الشتاء والتدفئة المتكاملة', en: 'Winter Package', aliases: ['winter package', 'باقة الشتاء والتدفئة المتكاملة'] },
  { ar: 'باقة التكنولوجيا والأنظمة الذكية المتطورة', en: 'Technology Package', aliases: ['technology package', 'باقة التكنولوجيا والأنظمة الذكية المتطورة'] },
  { ar: 'باقة مساعدة السائق والتحكم الذكي بالسرعة', en: 'Driver Assistance Package', aliases: ['driver assistance package', 'باقة مساعدة السائق والتحكم الذكي بالسرعة'] },
  { ar: 'الباقة المميزة الفاخرة Premium', en: 'Premium Package', aliases: ['premium package', 'الباقة المميزة الفاخرة premium'] },
  { ar: 'باقة بريميوم بلس الإضافية Premium Plus', en: 'Premium Plus Package', aliases: ['premium plus package', 'باقة بريميوم بلس الإضافية premium plus'] },
  { ar: 'الباقة الفاخرة القصوى بريستيج Prestige', en: 'Prestige Package', aliases: ['prestige package', 'الباقة الفاخرة القصوى بريستيج prestige'] },
  { ar: 'باقة الخيارات الكاملة الفول أوبشن Full Option', en: 'Full Option Package', aliases: ['full option package', 'full option', 'باقة الخيارات الكاملة الفول أوبشن full option'] },

  // الباقات الجديدة (New Packages)
  { ar: 'الباقة التنفيذية الفاخرة للقيادة والركاب', en: 'Executive Package', aliases: ['executive package', 'الباقة التنفيذية الفاخرة للقيادة والركاب'] },
  { ar: 'باقة السائق الخاصة بالتحكم وتعديل المقاعد', en: 'Chauffeur Package', aliases: ['chauffeur package', 'باقة السائق الخاصة بالتحكم وتعديل المقاعد'] },
  { ar: 'باقة الخصوصية والستائر الخلفية والجانبية المدمجة', en: 'Rear Privacy Package', aliases: ['rear privacy package', 'باقة الخصوصية والستائر الخلفية والجانبية المدمجة'] },
  { ar: 'باقة التدخين المتكاملة للمقاعد', en: 'Smoking Package', aliases: ['smoking package', 'باقة التدخين المتكاملة للمقاعد'] },
  { ar: 'باقة غير المدخنين الخالية من طفايات السجائر', en: 'Non-Smoking Package', aliases: ['non-smoking package', 'باقة غير المدخنين الخالية من طفايات السجائر'] },
  { ar: 'باقة الطاقس البارد والثلجي والتدفئة الشاملة', en: 'Cold Weather Package', aliases: ['cold weather package', 'باقة الطقس البارد والثلجي والتدفئة الشاملة'] },
  { ar: 'باقة الطقس الحار والتبريد الإضافي للمحرك والركاب', en: 'Hot Climate Package', aliases: ['hot climate package', 'باقة الطقس الحار والتبريد الإضافي للمحرك والركاب'] },
  { ar: 'باقة القطر والجر للمقطورات والربط المتطور', en: 'Tow Package', aliases: ['tow package', 'towing package', 'باقة القطر والجر للمقطورات والربط المتطور'] },
  { ar: 'باقة المغامرات والرحلات البرية الصعبة وتجهيزاتها', en: 'Adventure Package', aliases: ['adventure package', 'باقة المغامرات والرحلات البرية الصعبة'] },
  { ar: 'باقة المظهر الخارجي الأنيق واللمسات الجمالية', en: 'Appearance Package', aliases: ['appearance package', 'باقة المظهر الخارجي الأنيق'] },
  { ar: 'باقة كومبتيشن الرياضية والسرعة الفائقة', en: 'Competition Package', aliases: ['competition package', 'باقة كومبتيشن الرياضية والسرعة الفائقة'] },
  { ar: 'باقة إصدار التدشين المحدود والحصري للسيارة', en: 'Launch Edition Package', aliases: ['launch edition package', 'باقة إصدار التدشين المحدود والحصري'] },
  { ar: 'باقة الذكرى السنوية الخاصة بالشركة', en: 'Anniversary Package', aliases: ['anniversary package', 'باقة الذكرى السنوية الخاصة بالشركة'] },

  // وضعيات وحراسة إلكترونية وكهربائية (EV & Smart Tech Modes)
  { ar: 'سقف شمسي ذكي لتوليد الكهرباء وتشغيل المكيف', en: 'Solar Roof', aliases: ['solar roof', 'سقف شمسي ذكي لتوليد الكهرباء وتشغيل المكيف'] },
  { ar: 'سقف شحن شمسي متكامل لبطارية السيارة الرئيسية', en: 'Solar Charging Roof', aliases: ['solar charging roof', 'سقف شحن شمسي متكامل'] },
  { ar: 'وضعية التخييم وتشغيل الكهرباء والحرارة أثناء الوقوف', en: 'Camp Mode', aliases: ['camp mode', 'وضعية التخييم وتشغيل الكهرباء والحرارة أثناء الوقوف'] },
  { ar: 'وضعية حماية الحيوانات الأليفة مع الحفاظ على التكييف', en: 'Pet Mode', aliases: ['pet mode', 'وضعية حماية الحيوانات الأليفة'] },
  { ar: 'وضعية الحراسة والمراقبة بالكاميرات 360 أثناء الوقوف', en: 'Sentry Mode', aliases: ['sentry mode', 'وضعية الحراسة والمراقبة بالكاميرات 360 أثناء الوقوف'] },
  { ar: 'نظام تسجيل رحلات القيادة بكاميرات السيارة أوتوماتيكياً', en: 'Dash Recording', aliases: ['dash recording', 'نظام تسجيل رحلات القيادة بكاميرات السيارة أوتوماتيكياً'] },
  { ar: 'وضعية خدمة ركن السيارات وتقييد السرعة والمعلومات', en: 'Valet Mode', aliases: ['valet mode', 'وضعية خدمة ركن السيارات'] },
  { ar: 'نظام السياج الجغرافي وتحديد مناطق سير المركبة', en: 'Geo-Fencing', aliases: ['geo-fencing', 'geo fencing', 'نظام السياج الجغرافي'] },
  { ar: 'محدد السرعة القصوى الإلكتروني الآمن', en: 'Speed Limiter', aliases: ['speed limiter', 'محدد السرعة القصوى الإلكتروني الآمن'] },
  { ar: 'نظام فتح جراج المنزل الرقمي الذكي المدمج', en: 'Digital Garage Opener', aliases: ['digital garage opener', 'نظام فتح جراج المنزل الرقمي الذكي المدمج'] },
  { ar: 'مخارج تيار كهربائي قوية (110 فولت / 220 فولت)', en: 'Power Outlet (110V / 220V)', aliases: ['power outlet', 'power outlet (110v / 220v)'] },
  { ar: 'مخرج مقبس منزلي ثلاثي عادي 220 فولت بالشنطة', en: 'Household Socket', aliases: ['household socket', 'مخرج مقبس منزلي ثلاثي'] },
  { ar: 'تصدير الطاقة الكهربائية للأجهزة والمخيمات الخارجية', en: 'Portable Power Export', aliases: ['portable power export', 'تصدير الطاقة الكهربائية للأجهزة والمخيمات الخارجية'] },
  { ar: 'شحن ثنائي الاتجاه للبطارية وتزويد الشبكة بالطاقة', en: 'Bidirectional Charging', aliases: ['bidirectional charging', 'شحن ثنائي الاتجاه للبطارية'] },
  { ar: 'تسخين بطارية السيارة مسبقاً قبل الشحن للشحن الفائق', en: 'Battery Preheating', aliases: ['battery preheating', 'تسخين بطارية السيارة مسبقاً قبل الشحن للشحن الفائق'] },
  { ar: 'تهيئة وإعداد درجة حرارة البطارية للقيادة الرياضية والشحن', en: 'Battery Conditioning', aliases: ['battery conditioning', 'تهيئة وإعداد درجة حرارة البطارية للقيادة الرياضية والشحن'] }
]
